name: Deploy Frontend

on:
  push:
    branches: [main]

# ✅ REQUIRED for GitHub Pages Deploy to work
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Python tests
        run: |
          python -m unittest discover

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Copy frontend content
        run: |
          mkdir public
          cp -r frontend/* public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
